name: Build Loki Game Booster APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Buildozer
        run: |
          pip install --user --upgrade buildozer
          pip install --user --upgrade Cython==0.29.33

      - name: Instalar DependÃªncias do Sistema
        run: sudo apt-get install -y libpython3-dev git zip unzip zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget

      - name: Compilar APK (Buildozer)
        run: buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: LokiBooster-Debug
          path: bin/*.apk
